### ISSUE TITLE
Request for Batch Background Removal and API Control Functionality in Plugin

### ISSUE THREAD

**Issue by richadlee** [mattyamonaca/PBRemTools#2]
Hello,

I would like to request a feature for the current background removal plugin. Currently, it only allows manual removal of images one by one. I suggest adding a batch removal feature and an API for controlling the removal process. This would be very helpful for users who need to remove backgrounds from multiple images at once.

Thank you.

**Comment by Timboman** [comment]
Yes please, a batch option would be AMAZING.

**Comment by chace20** [comment]
@udon-universe Good Job! 👍  Have you implement the API? If not, I plan to implement the API functionality in the next few days.

**Comment by chace20** [comment]
The API impleted in PR https://github.com/mattyamonaca/PBRemTools/pull/30
